### ISSUE TITLE
Freeplane-zotero plugin not working anymore

### ISSUE THREAD

**Issue by Olifair** [petervelosy/freeplane-zotero#11]
I hadn't use the Zotero plugin since the last FreePlane update. and now when I right click a node and use "assign citations to node"
I get the following Error : 

Error executing Script: 
No such property: ui for class: assignCitationsToNode at line -1

using freeplane 1.11.11 and Zotero 6.0.36 and Freeplane- zotero plugin 0.1 (is there any other version?)

This is a pity, I have been using this plugin quite a lot. 

Cheers

Oliver

**Comment by petervelosy** [comment]
Dear Oliver,

First of all sorry for the very late reply, I was very full with "for-profit" projects in the last time and had little time for the open-source topics. 

Which operating system (type + version) do you use? Could you check if this still occurs with the latest FreePlane?  I've just checked freeplane-zotero 0.1 with Freeplane 1.12.6 and Zotero 6.0.37  on macOS 15 and could not reproduce this error.

Kind regards,
Peter

**Comment by Olifair** [comment]
Hello Peter, 
the problem has disappeared. I don't remember when, or what I did, but it has been working again for some while now :-)
but thanks for asking 
Oliver
