### ISSUE TITLE
Zotero 7 : will this plugin be working ? 

### ISSUE THREAD

**Issue by Olifair** [petervelosy/freeplane-zotero#12]
Hello, 
does anybody know if this plugin will still be working with Zotero 7 ? 

Cheers

Oliver

**Comment by petervelosy** [comment]
Dear Oliver,

I will download Zotero 7 and check. In any case, now that I have time to work on freeplane-zotero again, the goal is to make it work :-)

Kind regards,
Peter

**Comment by petervelosy** [comment]
Good news: The plugin works with Zotero 7 (tested with v7.0.9).

Feel free to open a new issue if you still encounter any incompatibility.

**Comment by Olifair** [comment]
Great, thanks a lot for checking this out 
I haven't gone to Zotero 7 yet, because I will have to decide with which plugin to replace ZotFile 
Oliver
