### ISSUE TITLE
FR - Add to the menu

### ISSUE THREAD

**Issue by bepolymathe** [petervelosy/freeplane-zotero#6]
Hi @petervelosy 

Nice to with a mouse but when you’re keyboard friendly like me, it would be great to be able to assign a shortcut to "`assign citation(s) to node`" command. 
I think it is not possible if the command is not in a main menu (tools --» Zotero for ex). 
I don't know what you think about it...

**Comment by petervelosy** [comment]
Adding the actions to the main menu as well is a great suggestion! However, I haven't found an elegant way to assign a script of an addon to multiple Freeplane menu locations (see my question here: https://github.com/freeplane/freeplane/discussions/967). 

There is a somewhat unelegant workaround: to duplicate the scripts under different file names inside the addon and assign different menu positions to them. This seems to work. Unless someone from the Freeplane community suggests a better way, I will implement it, as it indeed improves usability.

The good news is though: Freeplane allows using the "Assign hot key" feature on context menu items too! :-) So you can set hotkeys to every freeplane-zotero action.

**Comment by bepolymathe** [comment]
> This seems to work. Unless someone from the Freeplane community suggests a better way, I will implement it, as it indeed improves usability.

I have to check this in lilive ou macmarrum scripts...

**Comment by bepolymathe** [comment]
> The good news is though: Freeplane allows using the \"Assign hot key\" feature on context menu items too! :-) So you can set hotkeys to every freeplane-zotero action.

Really 🙃. I never find a way to do this... CTRL + click on context menu entry doesn't work for me.

**Comment by petervelosy** [comment]
> > The good news is though: Freeplane allows using the "Assign hot key" feature on context menu items too! :-) So you can set hotkeys to every freeplane-zotero action.
> 
> Really upside_down_face. I never find a way to do this... CTRL + click on context menu entry doesn't work for me.

Ctrl+click indeed doesn't work, but the following does: Tools > Assign hot key and then keep the dialog, that appears, open while clicking on the context menu item.

**Comment by bepolymathe** [comment]
So simple 🤣. Thanks 😃
